### ISSUE TITLE
Runtime errors on Windows

### ISSUE THREAD

**Issue by taxuexunshang** [fredericoschardong/post-quantum-oidc-oauth2#1]
Hello, I have encountered some problems and hope to get your help. When I run rp or app.py in the op directory on windows, TLS_SIGN is set to dilithium5 and JWT_SIGN is set to falcon512. At this time, Python will report ssl .SSLError: [SSL: EE_KEY_TOO_SMALL] ee key too small (_ssl.c:3862) error, hope to get your advice.

**Comment by fredericoschardong** [comment]
Hi @taxuexunshang.

I have never tested this code directly on Windows. I don't even own a copy of Windows to help you out. Please try to use Docker or run it directly on Ubuntu. Let me know if you have any issues.
